services:
  bff:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./todos.csv:/app/todos.csv
      - ./epics.csv:/app/epics.csv
      - ./spaces.csv:/app/spaces.csv
    restart: always
